<a href="https://colab.research.google.com/github/Baba123459876/100-days-of-machine-learning/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Fundaments of Tensorflow

In [1]:
import tensorflow as tf
print(tf.__version__)

2.8.2


In [2]:
#creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
#check the no. of dimensions of a tensor(ndim)
scalar.ndim


0

In [5]:
#create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
#check the dimension of vector
vector.ndim

1

In [10]:
#create a matrix
matrix = tf.constant([[10,7],
                      [3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [13]:
#create another matrix
another_matrix = tf.constant([[10.,7],
                              [3.,2],
                              [8.,9]], dtype = tf.float16) #flaot16, float32, float64
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [14]:
#create another matrix
another_matrix1 = tf.constant([[10.,7],
                              [3.,2],
                              [8.,9]], dtype = tf.float32) #flaot16, float32, float64
another_matrix1                              

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float32)>

In [15]:
#create another matrix
another_matrix2 = tf.constant([[10.,7],
                              [3.,2],
                              [8.,9]], dtype = tf.float64) #flaot16, float32, float64
another_matrix2       


<tf.Tensor: shape=(3, 2), dtype=float64, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]])>

In [18]:
#create a tensor
tensor = tf.constant([[[1,2,3,],
                       [4,5,6,]],
                       [[7,8,9,],[10,11,12,],],
                      [[13,14,15,],[16,17,18,]]], dtype=tf.int32)

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [19]:
tensor.ndim

3

Creating tensors with tf.Variable

In [20]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [22]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [23]:
#lest try and change an element of changeable tensor
changeable_tensor[0] = 7
changeable_tensor


TypeError: ignored

In [24]:
# TRY THIS .assign()
changeable_tensor[0].assign(7)
changeable_tensor


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [26]:
#lest try changing unchangeable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor


AttributeError: ignored