<a href="https://colab.research.google.com/github/Baba123459876/100-days-of-machine-learning/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Fundaments of Tensorflow

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.8.2


In [ ]:
#creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#check the no. of dimensions of a tensor(ndim)
scalar.ndim


0

In [ ]:
#create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#check the dimension of vector
vector.ndim

1

In [ ]:
#create a matrix
matrix = tf.constant([[10,7],
                      [3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
#create another matrix
another_matrix = tf.constant([[10.,7],
                              [3.,2],
                              [8.,9]], dtype = tf.float16) #flaot16, float32, float64
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
#create another matrix
another_matrix1 = tf.constant([[10.,7],
                              [3.,2],
                              [8.,9]], dtype = tf.float32) #flaot16, float32, float64
another_matrix1                              

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float32)>

In [ ]:
#create another matrix
another_matrix2 = tf.constant([[10.,7],
                              [3.,2],
                              [8.,9]], dtype = tf.float64) #flaot16, float32, float64
another_matrix2       


<tf.Tensor: shape=(3, 2), dtype=float64, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]])>

In [ ]:
#create a tensor
tensor = tf.constant([[[1,2,3,],
                       [4,5,6,]],
                       [[7,8,9,],[10,11,12,],],
                      [[13,14,15,],[16,17,18,]]], dtype=tf.int32)

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

Creating tensors with tf.Variable

In [ ]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [ ]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
#lest try and change an element of changeable tensor
changeable_tensor[0] = 7
changeable_tensor


TypeError: ignored

In [ ]:
# TRY THIS .assign()
changeable_tensor[0].assign(7)
changeable_tensor


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
#lest try changing unchangeable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor


AttributeError: ignored

In [ ]:
#Create Random Tensors
#tensors of arbitary size and random numbers

In [33]:
#create two random tensors with same nos.
random_1 = tf.random.Generator.from_seed(4) # set seed for reproducability
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(4) # set seed for reproducability
random_2 = random_2.normal(shape=(2,3))
random_1, random_2, random_1 == random_2


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 1.0019137 ,  0.6735137 ],
        [ 0.06987712, -1.4077919 ],
        [ 1.0278524 ,  0.27974114]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[ 1.0019137 ,  0.6735137 ,  0.06987712],
        [-1.4077919 ,  1.0278524 ,  0.27974114]], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=bool, numpy=False>)

In [34]:
## shuffle the order of elements in a tensor
# so that inherent learning is not affected when you shuffle data
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [5,6]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 5,  6]], dtype=int32)>

In [37]:
#shuffle our non-shuffled tensor
shuffled=tf.random.shuffle(not_shuffled)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 5,  6]], dtype=int32)>

In [43]:
tf.random.set_seed(42)
shuffle=tf.random.shuffle(not_shuffled, seed=42)
shuffle

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 5,  6]], dtype=int32)>

Read through Random seed generation  

#other ways tocreate **tensors**

In [44]:
#all ones tensor
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [45]:
#all zeros
tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

turn numpy arrays into tensors

In [47]:
#turning numpy array into tensors
import numpy as np
numpy_A = np.arange(1,25, dtype=np.int32) # create a numpy array between1 and 25
numpy_A
#X = tf.constant(some_matrix) # capital for tensor matrix
#y = tf.constant(vector) #non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [52]:
A=tf.constant(numpy_A, shape=(2,3,4)) # 3dimensions
B=tf.constant(numpy_A)
A.ndim, B

(3, <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [49]:
2*3*4

24

In [50]:
C=tf.constant(numpy_A, shape=(3,8)) # 3dimensions
B=tf.constant(numpy_A)
C, B 

(<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [51]:
A.ndim
B.ndim
C.ndim

2

#Getting information from tensors

* SHAPE    tensor.shape
*SIZE      tf.size(tensor)
*RANK       tensor.ndim
*AXIS/DIMENSION     tensor[0], tensor[:, 1]...

In [53]:
#create  a rank 4 tensor
rank_4_tensor = tf.zeros([2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_8_tensor = tf.zeros([2,3,4,5,6,7,8,9,10])
rank_8_tensor

In [58]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)
rank_8_tensor.shape, rank_8_tensor.ndim, tf.size(rank_8_tensor), tf.size(rank_8_tensor).numpy()

(TensorShape([2, 3, 4, 5, 6, 7, 8, 9, 10]),
 9,
 <tf.Tensor: shape=(), dtype=int32, numpy=3628800>,
 3628800)

#indexing tensors just like python lists

In [ ]:
#get the first 2 elements
rank_4_tensor[:2, :2,:2, :2]
#get the last 2 elements
rank_8_tensor[:2]